// Generated by https://quicktype.io

import { TerritoryInterface, UnitInterface } from "./types";

export interface Game {
  created_at:          string;
  current_territories: TerritoryInterface[];
  current_units:       UnitInterface[];
  game_phase:          string;
  game_state:          string;
  game_turn:           number;
  game_year:           number;
  id:                  number;
  name:                string;
  submit_deadline:     string;
}
